@REM Saxon engin and java locations
set SaxonLocation="C:\Program Files\Saxonica\SaxonHE9.9N\bin\Transform"
set JavaLocation="C:\Program Files\Java\jdk-11.0.9\bin\java.exe"


@REM Remove output folder
RMDIR "Output" /S /Q

@REM Exeucte System-Specific Transformations (SSTs)
@REM %SaxonLocation% -t project.xml Design-transformations/SSTs/SST_clean_observer.xsl
%SaxonLocation% -t project.xml Design-transformations/SSTs/SST_clean.xsl

@REM Merge partial PSMs generated by SITs of an SST
%JavaLocation% -jar XMLMergeTool.jar

@REM Generate code using M2T transformations (.NET)
%SaxonLocation% -t Output/MergedModel.xml M2T/DotNET/class_m2t_template.xsl

%SaxonLocation% -t Output/Models/enumerations.xml M2T/DotNET/enumeration_m2t_template.xsl 

%SaxonLocation% -t  Output/MergedModel.xml M2T/DotNET/interface_m2t_template.xsl

%SaxonLocation% -t  Output/Models/clean_architecture_projects.xml M2T/DotNET/dotnet_project_template.xsl

%SaxonLocation% -t  project.xml M2T/DotNET/base_specification_template.xsl

%SaxonLocation% -t  project.xml M2T/DotNET/util_template.xsl

%SaxonLocation% -t  project.xml M2T/DotNET/infra_ef_repository_template.xsl

%SaxonLocation% -t  project.xml M2T/DotNET/infra_specification_evaluator_template.xsl

